# Generated by Django 4.0.3 on 2022-06-17 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='active_ingredient',
        ),
        migrations.AddField(
            model_name='product',
            name='active_ingredient',
            field=models.ManyToManyField(to='products.activeingredient'),
        ),
        migrations.AlterField(
            model_name='product',
            name='med_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.medclass'),
        ),
    ]
