# Generated by Django 4.0.3 on 2022-06-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_med_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='med_image',
            field=models.ImageField(default=0, upload_to='D:\\pharmacy\\static\\img'),
        ),
    ]
